// Generated by gencpp from file grid_map_msgs/GetGridMap.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_GETGRIDMAP_H
#define GRID_MAP_MSGS_MESSAGE_GETGRIDMAP_H

#include <ros/service_traits.h>


#include <grid_map_msgs/GetGridMapRequest.h>
#include <grid_map_msgs/GetGridMapResponse.h>


namespace grid_map_msgs
{

struct GetGridMap
{

typedef GetGridMapRequest Request;
typedef GetGridMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGridMap
} // namespace grid_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_map_msgs::GetGridMap > {
  static const char* value()
  {
    return "802c2cbc7b10fada2d44db75ddb8c738";
  }

  static const char* value(const ::grid_map_msgs::GetGridMap&) { return value(); }
};

template<>
struct DataType< ::grid_map_msgs::GetGridMap > {
  static const char* value()
  {
    return "grid_map_msgs/GetGridMap";
  }

  static const char* value(const ::grid_map_msgs::GetGridMap&) { return value(); }
};


// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapRequest> should match
// service_traits::MD5Sum< ::grid_map_msgs::GetGridMap >
template<>
struct MD5Sum< ::grid_map_msgs::GetGridMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::GetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::GetGridMapRequest> should match
// service_traits::DataType< ::grid_map_msgs::GetGridMap >
template<>
struct DataType< ::grid_map_msgs::GetGridMapRequest>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::GetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapResponse> should match
// service_traits::MD5Sum< ::grid_map_msgs::GetGridMap >
template<>
struct MD5Sum< ::grid_map_msgs::GetGridMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::GetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::GetGridMapResponse> should match
// service_traits::DataType< ::grid_map_msgs::GetGridMap >
template<>
struct DataType< ::grid_map_msgs::GetGridMapResponse>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::GetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_GETGRIDMAP_H
