// Generated by gencpp from file grid_map_msgs/GetGridMapInfo.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_GETGRIDMAPINFO_H
#define GRID_MAP_MSGS_MESSAGE_GETGRIDMAPINFO_H

#include <ros/service_traits.h>


#include <grid_map_msgs/GetGridMapInfoRequest.h>
#include <grid_map_msgs/GetGridMapInfoResponse.h>


namespace grid_map_msgs
{

struct GetGridMapInfo
{

typedef GetGridMapInfoRequest Request;
typedef GetGridMapInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGridMapInfo
} // namespace grid_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_map_msgs::GetGridMapInfo > {
  static const char* value()
  {
    return "a0be1719725f7fd7b490db4d64321ff2";
  }

  static const char* value(const ::grid_map_msgs::GetGridMapInfo&) { return value(); }
};

template<>
struct DataType< ::grid_map_msgs::GetGridMapInfo > {
  static const char* value()
  {
    return "grid_map_msgs/GetGridMapInfo";
  }

  static const char* value(const ::grid_map_msgs::GetGridMapInfo&) { return value(); }
};


// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapInfoRequest> should match
// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapInfo >
template<>
struct MD5Sum< ::grid_map_msgs::GetGridMapInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::GetGridMapInfo >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::GetGridMapInfoRequest> should match
// service_traits::DataType< ::grid_map_msgs::GetGridMapInfo >
template<>
struct DataType< ::grid_map_msgs::GetGridMapInfoRequest>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::GetGridMapInfo >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapInfoResponse> should match
// service_traits::MD5Sum< ::grid_map_msgs::GetGridMapInfo >
template<>
struct MD5Sum< ::grid_map_msgs::GetGridMapInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::GetGridMapInfo >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::GetGridMapInfoResponse> should match
// service_traits::DataType< ::grid_map_msgs::GetGridMapInfo >
template<>
struct DataType< ::grid_map_msgs::GetGridMapInfoResponse>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::GetGridMapInfo >::value();
  }
  static const char* value(const ::grid_map_msgs::GetGridMapInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_GETGRIDMAPINFO_H
