// Generated by gencpp from file grid_map_msgs/GridMapInfo.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_GRIDMAPINFO_H
#define GRID_MAP_MSGS_MESSAGE_GRIDMAPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace grid_map_msgs
{
template <class ContainerAllocator>
struct GridMapInfo_
{
  typedef GridMapInfo_<ContainerAllocator> Type;

  GridMapInfo_()
    : header()
    , resolution(0.0)
    , length_x(0.0)
    , length_y(0.0)
    , pose()  {
    }
  GridMapInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , length_x(0.0)
    , length_y(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _resolution_type;
  _resolution_type resolution;

   typedef double _length_x_type;
  _length_x_type length_x;

   typedef double _length_y_type;
  _length_y_type length_y;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GridMapInfo_

typedef ::grid_map_msgs::GridMapInfo_<std::allocator<void> > GridMapInfo;

typedef boost::shared_ptr< ::grid_map_msgs::GridMapInfo > GridMapInfoPtr;
typedef boost::shared_ptr< ::grid_map_msgs::GridMapInfo const> GridMapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grid_map_msgs::GridMapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grid_map_msgs::GridMapInfo_<ContainerAllocator1> & lhs, const ::grid_map_msgs::GridMapInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resolution == rhs.resolution &&
    lhs.length_x == rhs.length_x &&
    lhs.length_y == rhs.length_y &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grid_map_msgs::GridMapInfo_<ContainerAllocator1> & lhs, const ::grid_map_msgs::GridMapInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grid_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43ee5430e1c253682111cb6bedac0ef9";
  }

  static const char* value(const ::grid_map_msgs::GridMapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43ee5430e1c25368ULL;
  static const uint64_t static_value2 = 0x2111cb6bedac0ef9ULL;
};

template<class ContainerAllocator>
struct DataType< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grid_map_msgs/GridMapInfo";
  }

  static const char* value(const ::grid_map_msgs::GridMapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header (time and frame)\n"
"Header header\n"
"\n"
"# Resolution of the grid [m/cell].\n"
"float64 resolution\n"
"\n"
"# Length in x-direction [m].\n"
"float64 length_x\n"
"\n"
"# Length in y-direction [m].\n"
"float64 length_y\n"
"\n"
"# Pose of the grid map center in the frame defined in `header` [m].\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::grid_map_msgs::GridMapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.length_x);
      stream.next(m.length_y);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridMapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grid_map_msgs::GridMapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grid_map_msgs::GridMapInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
    s << indent << "length_x: ";
    Printer<double>::stream(s, indent + "  ", v.length_x);
    s << indent << "length_y: ";
    Printer<double>::stream(s, indent + "  ", v.length_y);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_GRIDMAPINFO_H
