// Generated by gencpp from file grid_map_msgs/ProcessFile.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_PROCESSFILE_H
#define GRID_MAP_MSGS_MESSAGE_PROCESSFILE_H

#include <ros/service_traits.h>


#include <grid_map_msgs/ProcessFileRequest.h>
#include <grid_map_msgs/ProcessFileResponse.h>


namespace grid_map_msgs
{

struct ProcessFile
{

typedef ProcessFileRequest Request;
typedef ProcessFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessFile
} // namespace grid_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_map_msgs::ProcessFile > {
  static const char* value()
  {
    return "03f389710f49a6dd2a8b447bb2850cd6";
  }

  static const char* value(const ::grid_map_msgs::ProcessFile&) { return value(); }
};

template<>
struct DataType< ::grid_map_msgs::ProcessFile > {
  static const char* value()
  {
    return "grid_map_msgs/ProcessFile";
  }

  static const char* value(const ::grid_map_msgs::ProcessFile&) { return value(); }
};


// service_traits::MD5Sum< ::grid_map_msgs::ProcessFileRequest> should match
// service_traits::MD5Sum< ::grid_map_msgs::ProcessFile >
template<>
struct MD5Sum< ::grid_map_msgs::ProcessFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::ProcessFile >::value();
  }
  static const char* value(const ::grid_map_msgs::ProcessFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::ProcessFileRequest> should match
// service_traits::DataType< ::grid_map_msgs::ProcessFile >
template<>
struct DataType< ::grid_map_msgs::ProcessFileRequest>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::ProcessFile >::value();
  }
  static const char* value(const ::grid_map_msgs::ProcessFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_map_msgs::ProcessFileResponse> should match
// service_traits::MD5Sum< ::grid_map_msgs::ProcessFile >
template<>
struct MD5Sum< ::grid_map_msgs::ProcessFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::ProcessFile >::value();
  }
  static const char* value(const ::grid_map_msgs::ProcessFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::ProcessFileResponse> should match
// service_traits::DataType< ::grid_map_msgs::ProcessFile >
template<>
struct DataType< ::grid_map_msgs::ProcessFileResponse>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::ProcessFile >::value();
  }
  static const char* value(const ::grid_map_msgs::ProcessFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_PROCESSFILE_H
