// Generated by gencpp from file grid_map_msgs/ProcessFileResponse.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_PROCESSFILERESPONSE_H
#define GRID_MAP_MSGS_MESSAGE_PROCESSFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grid_map_msgs
{
template <class ContainerAllocator>
struct ProcessFileResponse_
{
  typedef ProcessFileResponse_<ContainerAllocator> Type;

  ProcessFileResponse_()
    : success(false)  {
    }
  ProcessFileResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessFileResponse_

typedef ::grid_map_msgs::ProcessFileResponse_<std::allocator<void> > ProcessFileResponse;

typedef boost::shared_ptr< ::grid_map_msgs::ProcessFileResponse > ProcessFileResponsePtr;
typedef boost::shared_ptr< ::grid_map_msgs::ProcessFileResponse const> ProcessFileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator1> & lhs, const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator1> & lhs, const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grid_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grid_map_msgs/ProcessFileResponse";
  }

  static const char* value(const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# True if file processing was successful.\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessFileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grid_map_msgs::ProcessFileResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_PROCESSFILERESPONSE_H
