// Generated by gencpp from file grid_map_msgs/SetGridMap.msg
// DO NOT EDIT!


#ifndef GRID_MAP_MSGS_MESSAGE_SETGRIDMAP_H
#define GRID_MAP_MSGS_MESSAGE_SETGRIDMAP_H

#include <ros/service_traits.h>


#include <grid_map_msgs/SetGridMapRequest.h>
#include <grid_map_msgs/SetGridMapResponse.h>


namespace grid_map_msgs
{

struct SetGridMap
{

typedef SetGridMapRequest Request;
typedef SetGridMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGridMap
} // namespace grid_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_map_msgs::SetGridMap > {
  static const char* value()
  {
    return "4f8e24cfd42bc1470fe765b7516ff7e5";
  }

  static const char* value(const ::grid_map_msgs::SetGridMap&) { return value(); }
};

template<>
struct DataType< ::grid_map_msgs::SetGridMap > {
  static const char* value()
  {
    return "grid_map_msgs/SetGridMap";
  }

  static const char* value(const ::grid_map_msgs::SetGridMap&) { return value(); }
};


// service_traits::MD5Sum< ::grid_map_msgs::SetGridMapRequest> should match
// service_traits::MD5Sum< ::grid_map_msgs::SetGridMap >
template<>
struct MD5Sum< ::grid_map_msgs::SetGridMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::SetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::SetGridMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::SetGridMapRequest> should match
// service_traits::DataType< ::grid_map_msgs::SetGridMap >
template<>
struct DataType< ::grid_map_msgs::SetGridMapRequest>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::SetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::SetGridMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_map_msgs::SetGridMapResponse> should match
// service_traits::MD5Sum< ::grid_map_msgs::SetGridMap >
template<>
struct MD5Sum< ::grid_map_msgs::SetGridMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_map_msgs::SetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::SetGridMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_map_msgs::SetGridMapResponse> should match
// service_traits::DataType< ::grid_map_msgs::SetGridMap >
template<>
struct DataType< ::grid_map_msgs::SetGridMapResponse>
{
  static const char* value()
  {
    return DataType< ::grid_map_msgs::SetGridMap >::value();
  }
  static const char* value(const ::grid_map_msgs::SetGridMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_MAP_MSGS_MESSAGE_SETGRIDMAP_H
