grid_map_topic: /uvc_grid_map/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: energy
  - name: occ_grid
    type: occupancy_grid
    params:
     layer: occupancy
     data_min: -1.0
     data_max: 100
  - name: visual
    type: occupancy_grid
    params:
     layer: visual
     data_min: -1.0
     data_max: 1.0
